[versions]
minecraft = "1.21.1"
fabric-loader = "0.19.3"
fabric-api = "0.116.15+1.21.1"
fabric-loom = "1.17.19"
moddev = "2.0.144"
modrinth = "2.9.0"
neoforge = "21.1.248"
mixin = "0.17.3+mixin.0.8.7"

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
neoforge-moddev = { id = "net.neoforged.moddev", version.ref = "moddev" }
modrinth = { id = "com.modrinth.minotaur", version.ref = "modrinth" }
