name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Build
        run: ./gradlew build --no-daemon

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: gutags
          path: '**/build/libs/*.jar'
