name: Release

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        loader:
          - fabric
          - neoforge

    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      - name: Publish to Modrinth
        run: ./gradlew :${{ matrix.loader }}:modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
